[player_base]
max_life = 100
current_life = 100
move_speed = 1.0
pickup_radius = 2.0
skill_slots_active = 0
damage_add_percent = 0
damage_final_percent = 0
attack_speed_add_percent = 0
cast_speed_add_percent = 0
skill_speed_final_percent = 0
cooldown_reduction_percent = 0
added_cooldown_ms = 0
area_add_percent = 0
projectile_count_add = 0
projectile_speed_add_percent = 0
crit_chance_add_percent = 0
crit_damage_add_percent = 0
status_chance_add_percent = 0
physical_damage_add_percent = 0
fire_damage_add_percent = 0
cold_damage_add_percent = 0
lightning_damage_add_percent = 0
