[drop_pool.gem_basic]
entries = [
  { tag = "active_skill_gem", weight = 300 },
  { tag = "passive_skill_gem", weight = 200 },
  { tag = "support_gem", weight = 500 },
]

[drop_pool.active_skill_gems]
entries = [
  { id = "active_fire_bolt", weight = 100 },
  { id = "active_ice_shards", weight = 100 },
  { id = "active_lightning_chain", weight = 100 },
  { id = "active_frost_nova", weight = 100 },
  { id = "active_puncture", weight = 100 },
  { id = "active_penetrating_shot", weight = 100 },
  { id = "active_lava_orb", weight = 100 },
  { id = "active_fungal_petards", weight = 100 },
]

[drop_pool.support_gems]
entries = [
  { tag = "gem_type_3", weight = 400 },
  { tag = "gem_type_4", weight = 120 },
  { tag = "gem_type_5", weight = 250 },
  { tag = "gem_type_8", weight = 100 },
  { tag = "gem_type_9", weight = 150 },
  { tag = "support_shape", weight = 250 },
]

[drop_pool.passive_skill_gems]
entries = [
  { id = "passive_fire_focus", weight = 120 },
  { id = "passive_vitality", weight = 100 },
  { id = "passive_swift_gathering", weight = 100 },
]
